paths:
  scomatic_dir: "/uoa/scratch/shared/Morgan_Lab/common_resources/SComatic"
  ref_dir: "/uoa/scratch/shared/Morgan_Lab/common_resources/hg38/chroms"
  bam_dir: "/uoa/home/r04mr23/sharedscratch/trial/scomatic/data/bam"
  scripts_dir: "/uoa/home/r04mr23/sharedscratch/trial/scomatic/SomaticMutationPipeline/scripts"

inputs:
  cell_type_annotations: "/uoa/scratch/shared/Morgan_Lab/tcell_ageing_meta_analysis_2023/data/soskic_2022/metadata/cell_metadata/cell_metadata_w_cell_type.csv"
  cell_type_column: "Cell_culture_batch"
  sra_metadata: "/uoa/scratch/shared/Morgan_Lab/tcell_ageing_meta_analysis_2023/data/soskic_2022/metadata/cell_metadata/cell_metadata_w_cell_type.csv"
  panel_of_normals: "/uoa/scratch/shared/Morgan_Lab/common_resources/SComatic/PoNs/PoN.scRNAseq.hg38.tsv"
  rna_editing_sites: "/uoa/scratch/shared/Morgan_Lab/common_resources/SComatic/RNAediting/AllEditingSites.hg38.txt"
  umap_bed_file: "/uoa/scratch/shared/Morgan_Lab/common_resources/SComatic/bed_files_of_interest/UCSC.k100_umap.without.repeatmasker.bed"
  
params:
  split_bams:
    window: 5000000 

  variant_calling:
    min_cells: 5
    min_ac_cells: 2
    min_ac_reads: 3
    max_cell_types: 6
    min_cell_types: 1
    fisher_cutoff: 0.001