# Environment settings
conda_env: "SComatic"
conda_prefix: ""  # Update all paths

# Paths
src_dir: ""
scomatic_dir: ""
ref_dir: ""
bam_dir: ""

# Input files for cell type splitting
cell_type_file: ""  # Maps cell barcodes to types
sra_metadata: ""    # Contains batch information

# batch information
batch_position: ""
batch_column: ""

# cell types comma separated list - NO SPACES
celltypes: ""

# genome chunk size for parallel BAM splitting - integer
window: 0

panel_of_normals: "/path/to/SComatic/PoNs/PoN.scRNAseq.hg38.tsv"
rna_editing_sites: "/path/to/SComatic/RNAediting/AllEditingSites.hg38.txt"

# Additional parameters for SComatic - numeric
min_cells: 5
min_ac_cells: 2
min_ac_reads: 3
max_cell_types: 6
min_cell_types: 1
fisher_cutoff: 0.001

# germline variant filtering
germline_filter: "filter_germline.R"